### ISSUE TITLE
The Page isn't Working is coming if we cancel the Payment.

### ISSUE THREAD

**Issue by somunelavalli** [bankopen/layer-magento-plugin_232#3]
If we cancel the payment we are getting the page like

This Page isn't working.
xyz.com is currently unable to handle this request.
HTP ERROR 500
![Openmoney_Issue](https://user-images.githubusercontent.com/47572851/108696654-da34cd80-7527-11eb-91b0-abec9642348b.PNG)

**Comment by asif0777** [comment]
@somunelavalli This issue has been fixed.  Could you please check now .
